/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectocitas;

import javax.swing.JOptionPane;

/**
 *
 * @author Roberto
 */
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public VentanaInicio() {
        initComponents();
        jDesktopPane1.setBorder(new ImagenFondo());
        setSize(1366, 768);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ItemClientes = new javax.swing.JMenuItem();
        ItemCitas = new javax.swing.JMenuItem();
        ItemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ItemAcercade = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Citas v1.0");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ItemClientes.setText("Clientes");
        ItemClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemClientesActionPerformed(evt);
            }
        });
        jMenu1.add(ItemClientes);

        ItemCitas.setText("Citas");
        ItemCitas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ItemCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemCitasActionPerformed(evt);
            }
        });
        jMenu1.add(ItemCitas);

        ItemSalir.setText("Salir");
        ItemSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(ItemSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acerca de");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ItemAcercade.setText("Acerca de");
        ItemAcercade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ItemAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemAcercadeActionPerformed(evt);
            }
        });
        jMenu2.add(ItemAcercade);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemClientesActionPerformed
        if (ventanaclientes.isVisible() == false) {
            jDesktopPane1.add(ventanaclientes);
            ventanaclientes.show();
        }
    }//GEN-LAST:event_ItemClientesActionPerformed

    private void ItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ItemSalirActionPerformed

    private void ItemAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemAcercadeActionPerformed
        JOptionPane.showMessageDialog(this, "Creado por Roberto Priego");
    }//GEN-LAST:event_ItemAcercadeActionPerformed

    private void ItemCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCitasActionPerformed
        ventanaAgenda=new HorasCitas();
        if (ventanaAgenda.isVisible() == false) {
            jDesktopPane1.add(ventanaAgenda);
            ventanaAgenda.show();
        }
    }//GEN-LAST:event_ItemCitasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemAcercade;
    private javax.swing.JMenuItem ItemCitas;
    private javax.swing.JMenuItem ItemClientes;
    private javax.swing.JMenuItem ItemSalir;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
    Clientes ventanaclientes = new Clientes();
    HorasCitas ventanaAgenda = null;

}
